version: "3.0"

services:
  influxdb:
    image: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
      - "2003:2003"
    environment:
      - INFLUXDB_DB=grafana
      - INFLUXDB_USER=grafana
      - INFLUXDB_USER_PASSWORD=grafana
      - INFLUXDB_GRAPHITE_ENABLED=true
    restart: always

